### PR TITLE
Ionic4 elements

### PR DESCRIPTION
**Pull request by Devqon**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**
Adds support for Ionic 4 elements

**Please check if the PR fulfills these requirements**
- [x] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] A unit test has been written for this change.
- [ ] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [x] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**

**Other information**:

### CODE REVIEW

**Comment by aitboudad** [comment]
the demo should work now, can you check if every things work as expected before merging and Thanks!

**Comment by Devqon** [comment]
Great thank you!

**Comment by aitboudad** [comment]
Thank you @Devqon!

**Comment by damsorian** [comment]
Hi @Devqon!  how I can to set the floating label to inputs?

**Comment by Devqon** [comment]
> Hi @Devqon! how I can to set the floating label to inputs?

You can use `labelPosition` on the templateOptions:

```
var field = {
    templateOptions: {
        label: 'Some label',
        labelPosition: 'floating'
    }
};
```

**Comment by damsorian** [comment]
hi @Devqon! thanks! but that is not working for me, do you know a demo with that feature?

**Comment by aitboudad** [comment]
@damsorian only available in the beta version for now

**Comment by damsorian** [comment]
@aitboudad nice!, I will check that version now, thanks!

**Comment by aitboudad** [comment]
right now I'm waiting for ionic to release a v4 stable version.

**Pull request merged**
