### PR TITLE
The same ValidationErrors wants to prompt different information, based on the value entered

### PR DESCRIPTION
**Pull request by smile2014**
Chinese ID card 15 and 18 valid check
export function  cardValidator(control: FormControl): ValidationErrors {
  let message ="";
   if(card === '')
    {
        message = 'card can't is not null';
        return false;
    }
    if(isCardNo(card) === false)
    {
        message='card can't correct';
        return false;
    }
    if(checkProvince(card) === false)
    {
        message='card can't correct';
        return false;
    }
    if(checkBirthday(card) === false)
    {
        message='card can't correct';
        return false;
    }
}

### CODE REVIEW

**Comment by smile2014** [comment]
@aitboudad  Can write multiple valid, but that's too much trouble 
Can you give me some advice, thank you?

**Comment by aitboudad** [comment]
sorry, but your question is not clear to me!

**Comment by aitboudad** [comment]
the message can be passed as a function see https://formly-js.github.io/ngx-formly/examples/validation/validation-message

**Comment by smile2014** [comment]
I know, but the same processor can't prompt different messages.
For example
https://github.com/ScottMGerstl/ng2-validate/blob/master/demo/email.validator.ts

**Comment by smile2014** [comment]
@aitboudad 
This configuration allows erros to read this message and find that ngx-formly does not support this.

export function IpValidator(control: FormControl): ValidationErrors {
  return !control.value || /(\d{1,3}\.){3}\d{1,3}/.test(control.value) ? null : { 'ip': true,message:'testerro' };
}

**Comment by aitboudad** [comment]
we don't support that case yet, just opened an issue for that #1303

**Comment by smile2014** [comment]
@aitboudad  thank you ，the problem has been solved
export function IpValidator(control: FormControl): ValidationErrors {
return !control.value || /(\d{1,3}.){3}\d{1,3}/.test(control.value) ? null : { 'ip': {message:'customMessage'} };
}

**Comment by aitboudad** [comment]
seems already supported [FormlyValidationMessage:L27](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/lib/templates/formly.validation-message.ts#L27) :), I'll try to add it in the demo example.

**Comment by smile2014** [comment]
@aitboudad thank you

**Pull request closed without merging**
