### PR TITLE
feat(ionic): initial work for ui-ionic support

### PR DESCRIPTION
**Pull request by thm1118**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Ionic support

**What is the current behavior? (You can also link to an open issue here)**

#646 

**What is the new behavior (if this is a feature change)?**

**Please check if the PR fulfills these requirements**
- [ ] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] A unit test has been written for this change.
- [ *] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [ ] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**

**Other information**:

---
This change is [Reviewable](https://reviewable.io/reviews/formly-js/ngx-formly/659)

### CODE REVIEW

**Comment by aitboudad** [comment]
I need to find a little time to test it.

**Comment by uakdemir** [comment]
It would be great for our mobile focused project - thank you for the amazing work, please try to prioritize this one when you have the chance.

**Comment by aitboudad** [comment]
moved to `v3` milestone, since we're close to release `V2`.
The next major version we will focus on adding more UI templates such as IONIC, NATIVESCRIPT + NgBootstrap and  more types like DatePicker, Autocomplete and more.
This PR will be the first one that I'll take care of it. stay tuned and sorry for taking all that time.

**Comment by aitboudad** [comment]
Thank you @thm1118!

**Pull request merged**
