### PR TITLE
Issue 528/support update on

### PR DESCRIPTION
**Pull request by samtsai**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Additional tests to existing FormlyForm component.

**What is the current behavior? (You can also link to an open issue here)**

No demonstrated support for `updateOn`, see #528 

**What is the new behavior (if this is a feature change)?**

No actual code changes as of yet, first just showing that `updateOn` works if applied correctly on FormGroups.

**Please check if the PR fulfills these requirements**
- [X] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [X] A unit test has been written for this change.
- [X] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [X] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**

**Other information**:

We can discuss what API changes we should make to support `updateOn` (e.g. via templateOptions?)

### CODE REVIEW

**Comment by samtsai** [comment]
Tests were largely benefited from Angular's tests: https://github.com/angular/angular/blob/4648597d14e843f75c5e9dd761af740c1c27b5c0/packages/forms/test/reactive_integration_spec.ts

**Comment by samtsai** [comment]
@mohammedzamakhan @aitboudad this is just adding tests to existing features, but I wanted to see what you guys thought in terms of API updates to pass `updateOn` settings to Form Controls the "@ngx-formly" way.

**Comment by aitboudad** [comment]
@samtsai similar to the [angularjs version](http://angular-formly.com/#!/example/field-options/model-options), introduction a new option `updateOn` in [FormlyFieldConfig](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/lib/components/formly.field.config.ts#L140) would be enough

```ts
modelOptions: {
  updateOn: 'blur' // 'submit' | 'blur'
}
```

for the global one I think it can be done by end users when passing a custom form input:
```ts
form = new FormGroup({}, {updateOn: 'submit'});
```

**Comment by samtsai** [comment]
As you wish :), I'll take a look at this today.

**Comment by samtsai** [comment]
@aitboudad I've updated the PR to use `modelOptions` with tests and updated examples.

**Comment by aitboudad** [comment]
@samtsai awesome work :tada::tada:, thank you!

**Comment by voznik** [comment]
guys, can you release this feature in core@3.x ? we need this for Angular 5

**Comment by samtsai** [comment]
@voznik I'll take a look and see if I can cherry-pick. Running through the tests now.

cc @aitboudad

**Comment by samtsai** [comment]
I've created a PR: https://github.com/formly-js/ngx-formly/pull/990, since I don't know how older releases work I'm pointing to `master` until it can be re-routed.

**Comment by aitboudad** [comment]
@voznik features are only added in the latest version, https://github.com/formly-js/ngx-formly/issues/944#issuecomment-388012741

**Pull request merged**
