### PR TITLE
add schematics

### PR DESCRIPTION
**Pull request by samtsai**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Feature for #644 

**What is the current behavior? (You can also link to an open issue here)**

No schematics

**What is the new behavior (if this is a feature change)?**

Add schematics to install `ng add` Formly core and theme

**Please check if the PR fulfills these requirements**
- [X] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [X] A unit test has been written for this change.
- [X] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [X] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**

**Other information**:

There's still a good amount of work to be done.

- [x] Finish `wrapper` component schematic
- [x] Test drive schematics in a project
- [x] Determine how to package schematics (via `core`? its own lib?)
- [x] Update documentation to include schematic steps

I did not build it as a lib and not sure how to use `ng-packagr` with it yet. Also the tests are more basic and are run by calling `npm run test` which compiles the TS files and runs `jasmine`.

### CODE REVIEW

**Comment by juristr** [comment]
Wow awesome @samtsai 😍. Didn't yet look at the details of ur PR yet, but allowing people to install ngx-formly with the new ng add command will be nice 👏

**Comment by samtsai** [comment]
@aitboudad @juristr I'm working through how to package Schematics since it's not an Angular app/lib. I see two options and their usages:

* independent schematic package, install via `npm install -D @ngx-formly/schematics`, then you tell `angular.json` to point to these schematics – patterned after [@ngrx/schematics](https://github.com/ngrx/platform/blob/master/docs/schematics/README.md)
* package as part of `@ngx-formly/core` and then you can presumably do `ng add @ngx-formly/core --ui-theme=material` which kicks off the `ng-add` schematic

I like the first option because it keeps responsibilities separate but you don't get the benefit of `ng add` which I think, eventually will be the de facto way to add packages to your application/library (it's just lacks documentation right now). Thoughts?

**Comment by samtsai** [comment]
Looks like we can do something like what [ng-bootstrap](https://github.com/ng-bootstrap/schematics/pull/1) does (see https://youtu.be/IZEolKjcjks?t=514).

To add `ngx-formly` to a project, you would then do: `ng add @ngx-formly/schematics`

**Comment by samtsai** [comment]
@aitboudad I think we can start with this PR and then continue to improve schematics. Once `@ngx-formly/schematics` is published it will be easier to test.

**Comment by aitboudad** [comment]
@samtsai thanks, I'll take a look soon!

**Comment by thorgod** [comment]
@samtsai thanks I was looking on how to link it locally

**Comment by aitboudad** [comment]
Thank you @samtsai!

**Comment by samtsai** [comment]
@aitboudad I'll be on the look out if we run into any issues! Thanks!

**Pull request merged**
